#pragma once

//#define VENDOR_ID       0x544C	// "TL"
//#define PRODUCT_ID      0x3936	// "36"
//#define DEVICE_VER      0x0001
//#define MANUFACTURER    Talo Studio
//#define PRODUCT         TL96 Keyboard
//#define DESCRIPTION     Keyboard



#define MATRIX_ROWS 6
#define MATRIX_COLS 16

#define MATRIX_ROW_PINS \
	{ E6, F0, F1, D5, C7, C6 }
#define MATRIX_COL_PINS \
	{ F4, F5, F6, F7, B0, B1, B2, B3, D0, D1, D2, D3, D4, D6, D7, B4 }

/* COL2ROW, ROW2COL */
#define DIODE_DIRECTION COL2ROW



#define WS2812_DI_PIN B6
#define RGBLED_NUM 110
#define DRIVER_LED_TOTAL RGBLED_NUM
// #define RGB_MATRIX_KEYRELEASES // reacts to keyreleases (instead of keypresses)
//#define RGB_DISABLE_AFTER_TIMEOUT 5000 // number of ticks to wait until disabling effects
//#define RGB_DISABLE_WHEN_USB_SUSPENDED  // turn off effects when suspended
// #define RGB_MATRIX_LED_PROCESS_LIMIT (DRIVER_LED_TOTAL + 4) / 5 // limits the number of LEDs to process in an animation per task run (increases keyboard responsiveness)
// #define RGB_MATRIX_LED_FLUSH_LIMIT 16 // 以毫秒为单位限制动画更新 LED 的频率。 16（16ms）相当于限制为60fps（提高键盘响应速度）
//#define RGB_MATRIX_HUE_STEP 8
//#define RGB_MATRIX_SAT_STEP 8
//#define RGB_MATRIX_VAL_STEP 8
//#define RGB_MATRIX_SPD_STEP 10

#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_CYCLE_LEFT_RIGHT	//默认模式
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200			//最大亮度(0-255)
#define RGB_MATRIX_STARTUP_VAL 150				//默认亮度


#define RGB_MATRIX_KEYPRESSES  // reacts to keypresses
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS

//特效启用
#define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_BAND_SAT
#define ENABLE_RGB_MATRIX_BAND_VAL
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#define ENABLE_RGB_MATRIX_RAINDROPS
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define ENABLE_RGB_MATRIX_HUE_BREATHING
#define ENABLE_RGB_MATRIX_HUE_PENDULUM
#define ENABLE_RGB_MATRIX_HUE_WAVE
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#define ENABLE_RGB_MATRIX_PIXEL_FLOW
#define ENABLE_RGB_MATRIX_PIXEL_RAIN

#define ENABLE_RGB_MATRIX_TYPING_HEATMAP

#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH




//#define RGB_DI_PIN B6
//#define DRIVER_LED_TOTAL 110
//#define RGBLIGHT_LIMIT_VAL 150 /* The maximum brightness level */

//#define RGB_MATRIX_KEYPRESSES
//#define RGB_MATRIX_FRAMEBUFFER_EFFECTS


#define DEBOUNCE 5


